name: supcoder
description: "Supcoder Management System."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  flutter_svg: ^2.0.7
  provider: ^6.1.2
  flex_color_scheme: ^8.1.0
  fl_chart: ^0.69.2
  sqlite3_flutter_libs: ^0.5.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 正确的插件配置位置
  plugin:
    platforms:
      android:
        package: com.supcoder.supcoder.plugin
        pluginClass: SupcoderFlutterPlugin

# 如果你需要多个插件，可以使用 plugins 字段
# flutter:
#   plugins:
#     supcoder_flutter_plugin:
#       package: com.supcoder.supcoder.plugin
#       pluginClass: SupcoderFlutterPlugin
